server.port: 7021

server:
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.kenny: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt.secret: thisismyvrodasecretkey
jwt.jwtExpirationMs: 1800000
#jwt.jwtRefreshExpirationMs: 3600000

---
spring:
  jpa:
    hibernate:
      ddl-auto: update


spring.datasource:
  url: jdbc:mysql://b07fe163a20874:850cf198@us-cdbr-east-05.cleardb.net/heroku_5189b4bf1df1e3a?reconnect=true
  username: b07fe163a20874
  password: 850cf198
#spring.datasource:
#  url: jdbc:mysql://localhost:3306/vrodadb1
#  username: user
#  password: pwd

spring.datasource.hikari.initializationFailTimeout: 60000
---
spring.profiles: docker

spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://mysql31/vrodadb1
    username: user
    password: pwd
    initialization-mode: always


  jpa:
    hibernate:
      ddl-auto: update

spring.datasource.hikari.initializationFailTimeout: 60000

server.port: 8080

