server.port: 7021

server:
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.kenny: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt.secret: thisismyvrodasecretkey
jwt.jwtExpirationMs: 1800000
#jwt.jwtRefreshExpirationMs: 3600000

---
spring:
  jpa:
    hibernate:
      ddl-auto: update


spring.datasource:
  url: jdbc:mysql://bbc6a5a6ee5bdd:82f9ac32@us-cdbr-east-05.cleardb.net/heroku_897ab759ea43fc3?reconnect=true
  username: bbc6a5a6ee5bdd
  password: 82f9ac32
#spring.datasource:
#  url: jdbc:mysql://localhost:3306/vrodadb1
#  username: user
#  password: pwd

spring.datasource.hikari.initializationFailTimeout: 60000
---
spring.profiles: docker

spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://mysql31/vrodadb1
    username: user
    password: pwd
    initialization-mode: always


  jpa:
    hibernate:
      ddl-auto: update

spring.datasource.hikari.initializationFailTimeout: 60000

server.port: 8080

