services:
  product:
    build: microservices/product-service
    hostname: product
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql30:
        condition: service_healthy

  auth:
    build: microservices/auth-service
    hostname: auth
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql31:
        condition: service_healthy

  api:
    build: api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - product
      - auth
      - cart

  cart:
    build: microservices/cart-service
    hostname: cart
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql32:
        condition: service_healthy
#      - product


  mysql30:
    image: mysql:5.7
    platform: linux/amd64
    #mem_limit: 350m
    ports:
      - "3320:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=product-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    volumes:
      - ./data/mysql30:/var/lib/mysql30
      - ./data/init.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uuser", "-ppwd", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  mysql31:
    image: mysql:5.7
    platform: linux/amd64
    #mem_limit: 350m
    ports:
      - "3321:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=product-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    volumes:
      - ./data/mysql31:/var/lib/mysql31
      - ./data/init.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-uuser", "-ppwd", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10

  mysql32:
    image: mysql:5.7
    platform: linux/amd64
    #mem_limit: 350m
    ports:
      - "3322:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=cart-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    volumes:
      - ./data/mysql32:/var/lib/mysql32
      - ./data/init.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-uuser", "-ppwd", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
