server.port: 7021

server:
  error:
    include-message: always

app:
  product-service:
    host: localhost
    port: 7001
    
logging:
  level:
    root: INFO
    com.kenny: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt.secret: thisismyvrodasecretkey
jwt.exp: 1800000

---
spring:
  jpa:
    hibernate:
      ddl-auto: update


spring.datasource:
  url: jdbc:mysql://localhost:3306/vrodadb1
  username: user
  password: pwd

spring.datasource.hikari.initializationFailTimeout: 60000

---
spring.profiles: docker
server.port: 8080

spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://mysql31/vrodadb1
    username: user
    password: pwd
    initialization-mode: always


  jpa:
    hibernate:
      ddl-auto: update

spring.datasource.hikari.initializationFailTimeout: 60000

app:
  product-service:
    host: product
    port: 8080

