server.port: ${PORT:5000}
server.error.include-message: always

app:
  product-service:
    host: localhost
    port: ${PORT:5000}
  cart-service:
    host: localhost
    port: ${PORT:5000}

  auth-service:
    hots: localhost
    port: ${PORT:5000}

logging:
  level:
    root: INFO
    com.kenny: DEBUG

---
spring.profiles: docker
server.port: 8080

app:
  product-service:
    host: product
    port: 8080
  cart-service:
    host: cart
    port: 8080

  auth-service:
    host: auth
    port: 8080
